---
- name: Baseline worker nodes
  hosts: all
  tasks:
   - name: Install Chorny
     yum: name=chrony state=installed 
     tags: ntp
   

   - name: Make sure Chrony is started up
     service: name=chronyd state=started enabled=yes
     tags: chrony
   
   - name: "3.3.2 | L2 | PATCH | Ensure SCTP is disabled"
     lineinfile:
       dest: /etc/modprobe.d/CIS.conf
       regexp: "^(#)?install sctp(\\s|$)"
       line: "install sctp /bin/true"
       create: yes
       mode: 0600

   - name: "3.3.3 | L2 | PATCH | Ensure RDS is disabled"
     lineinfile:
       dest: /etc/modprobe.d/CIS.conf
       regexp: "^(#)?install rds(\\s|$)"
       line: "install rds /bin/true"
       create: yes
       mode: 0600

   - name: "3.3.4 | L2 | PATCH | Ensure TIPC is disabled"
     lineinfile:
       dest: /etc/modprobe.d/CIS.conf
       regexp: "^(#)?install tipc(\\s|$)"
       line: "install tipc /bin/true"
       create: yes
       mode: 0600
       
   - name: "4.1.1.1 | L2 | PATCH | Ensure auditd is installed | Install auditd packages"
     package:
       name: audit
       state: present
