---
- name: Openshift integrationn 
  hosts: all
  tasks:
   - name: Create a k8s namespace
     k8s:
       name: testing
       api_version: v1
       kind: Namespace
       state: present
     delegate_to: localhost
   - name: Deploy Redis Master-Slave architechture on Openshift
     k8s:
       state: present
       src: /root/deploy.yaml
     delegate_to: 192.168.40.119
  #     definition: "{{ lookup('file', '/root/deploy.yaml') | from_yaml }}"

