---
- name: Openshift integrationn 
  hosts: localhost
  tasks:
   - name: Create a k8s namespace
     k8s:
       name: testing
       api_version: v1
       kind: Namespace
       state: present
   - name: Deploy Redis Master-Slave architechture on Openshift
     k8s:
       state: present
       src: /root/deploy.yaml
     delegate_to: localhost
