---
- name: Openshift integrationn 
  hosts: all
  tasks:
   - name: Create a k8s namespace
     k8s:
       name: testing
       api_version: v1
       kind: Namespace
       state: present
     delegate_to: localhost
   - name: Create Service for redis-master
     k8s:
       state: present   
       definition:
         apiVersion: v1
         kind: Service
         metadata:
           name: redis-master
           namespace: testing
           labels:
             app: redis
             tier: backend
             role: master
         spec:
           ports:
           - port: 6379
             targetPort: 6379
           selector:
             app: redis
             tier: backend
             role: master
     delegate_to: localhost
   - name: Create deployment for redis master
     k8s:
       state: present   
       definition:
         apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
         kind: Deployment
         metadata:
           name: redis-master
           namespace: testing
         spec:
           selector:
             matchLabels:
               app: redis
               role: master
               tier: backend
           replicas: 1
           template:
             metadata:
               labels:
                 app: redis
                 role: master
                 tier: backend
             spec:
               containers:
               - name: master
                 image: k8s.gcr.io/redis:e2e  # or just image: redis
                 resources:
                   requests:
                     cpu: 100m
                     memory: 100Mi
                 ports:
                 - containerPort: 6379
     delegate_to: localhost    
