---
- name: Register an incident on SN
  hosts: all
  gather_facts: no
  tasks:
  - name: Create a incident
    servicenow.servicenow.snow_record:
      state: present
      username: admin
      password: lwj17dwSVWUK
      instance: dev117483
      data:
        severity: 3
        priority: 2
        short_description: "Machine set successfully scaled"
        description: "Machine set successfully scaled to desired count"
        category: Software
    register: new_incident
    delegate_to: localhost
  - debug: 
      var: new_incident.record
